config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :questions do
      resources :responses, shallow: true
    end
  end

  root 'static_pages#survey'

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  belongs_to :user
end

app/models/participant.rb
class Participant < User
  def self.find_safely(request, participant_token)
    Participant.where(token: participant_token).first_or_initialize do |participant|
      Environment.create(user: participant, user_agent: request.env['HTTP_USER_AGENT'])
      # we aren't using the email field, but it should be unique
      # removing the email field seems ill-advised, as it limits future extensibility
      participant.email = participant_token
      participant.save(validate: false) if participant.new_record?
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_one :response
  before_create :init

  def init
    last_sequence_id = Question.maximum(:sequence_id)
    self.sequence_id = last_sequence_id.to_i + 1
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :environment
  has_many :questions

  def update_current_question
    update(current_question: current_question + 1)
    save(validate: false) # need a better solution end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  # Lazy Registration adapted from https://www.bignerdranch.com/blog/lazy-user-registration-for-rails-apps/
  # see also http://stackoverflow.com/questions/14455375/anonymous-user-in-devise-rails
  def authenticate_user!(*args)
    current_user.present? || super(*args)
  end

  def current_user
    super || Participant.find_safely(request, participant_token)
  end

  private

  def participant_token
    session[:participant_token] ||= SecureRandom.uuid
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show]

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # # GET /questions/new
  # def new
  #   @question = Question.new
  # end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:type, :section_id, :sequence_id, :user_id)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    #N.B. that @question is the _next_ question in the sequence.
    @question = current_user.questions.new
    @question.type = "Question"
    @question.section_id = 1
    @question.save
    current_user.current_question = current_user.current_question + 1
  end

  # # GET /responses/new
  # def new
  #   @response = Response.new
  # end
  #

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    @question = Question.find(params[:question_id])
    @question.response = @response

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:type, :section_id, :sequence_id, :question_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper

  def survey
    view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #Order session data
  def render_question
    order = Order.find_by(orderable: current_user.current_question)
    if order == nil
      return order
    else
      McQuestion.find_by(id: order.mc_question_id)
    end
  end

  #Question session data
  def set_cur_question(id)
    session[:question_id] = id
    set_count
  end

  #Count
  def set_count(value = 1)
    session[:count] = value
  end

  def increment_count
    session[:count] = (session[:count].to_i+1).to_s
  end

  def current_count
    session[:count]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def view
    next_view
  end

  def next_view
    if current_user.current_question == 0 # 0 order render welcome
      @question = current_user.questions.new
      @question.type = "Question"
      @question.section_id = 1
      @question.save
      render template: 'static_pages/welcome'
    else # >0 order render finder or mc_question
      @next = render_question
      if @next.nil?
        render template: 'static_pages/thankyou'
      elsif @next.class == Finder
        if render_items # render_question the same for pair of question/pictures
          set_render_items false
          render_pictures
        else
          set_render_items true
        end
      elsif @next.class == McQuestion
        render_followup
      end
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Trigger Foods Survey
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .row
      .col-xs-8.col-xs-offset-2
        #main
          = yield
        #nav
    %footer= "Participant Token: #{session[:participant_token]}"
    = #debug(params) if Rails.env.development?

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :section_id
    = f.text_field :section_id
  .field
    = f.label :sequence_id
    = f.text_field :sequence_id
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/questions/_question.html.haml
%p
  %b Type:
  = @question.type
%p
  %b Section:
  = @question.section_id
%p
  %b Sequence:
  = @question.sequence_id

= button_to 'Next', user_question_responses_path(current_user, @question), remote: true, class: "btn btn-lg btn-primary center-block", params: { :"response[type]" => "Response" }

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %thead
    %tr
      %th Type
      %th Section
      %th Sequence
      %th User
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.type
        %td= question.section_id
        %td= question.sequence_id
        %td= question.user
        %td= link_to 'Show', question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/show.html.haml
%p#notice= notice

= render @question

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/responses/_form.html.haml
= form_for @response do |f|
  - if @response.errors.any?
    #error_explanation
      %h2= "#{pluralize(@response.errors.count, "error")} prohibited this response from being saved:"
      %ul
        - @response.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :question
    = f.text_field :question
  .actions
    = f.submit 'Save'

app/views/responses/index.html.haml
%h1 Listing responses

%table
  %thead
    %tr
      %th Type
      %th Question
      %th
      %th
      %th

  %tbody
    - @responses.each do |response|
      %tr
        %td= response.type
        %td= response.question
        %td= link_to 'Show', response
        %td= link_to 'Edit', edit_response_path(response)
        %td= link_to 'Destroy', response, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Response', new_response_path

app/views/responses/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @response.type
%p
  %b Question:
  = @response.question

= link_to 'Edit', edit_response_path(@response)
\|
= link_to 'Back', responses_path

app/views/responses/show.js.erb
//render the _next_ question, which is confusingly named '@question'
$("#main").html("<%= escape_javascript(render @question) %>");

app/views/static_pages/thankyou.html.haml
= content_tag :div,'', id: "page_type", data: {type: @type}
.center
  %h1 Great job!
  %h6 Please raise your hand to let us know you are finished.

app/views/static_pages/welcome.html.haml
%h1 Welcome!
%p.text-left Thank you for agreeing to participate in our survey. This survey is being used for a graduate research study at CSU, Chico in partnership with the Center for Healthy Communities. The results from this study will help us learn about food and beverage consumption, specifically  foods that people over-consume. These foods usually have higher amounts of fat and sugar and can lead to overeating and can be referred to as problematic or trigger foods.
%p.text-left Participation in this survey is voluntary and anonymous. If at any point you do not want to continue the survey, you may stop. There is absolutely no risk in participating in this study.

= button_to 'Start', user_question_responses_path(current_user, @question), remote: true, class: "btn btn-lg btn-primary center-block", params: { :"response[type]" => "Response" }